# Generated by Django 3.1 on 2020-09-09 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='atttendes',
            field=models.ManyToManyField(blank=True, to='program.Member'),
        ),
    ]
