# Generated by Django 3.1 on 2020-09-09 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0002_auto_20200909_1418'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='atttendes',
            new_name='attendes',
        ),
    ]
