# Generated by Django 3.1 on 2020-09-09 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0006_auto_20200909_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='attendes',
            field=models.ManyToManyField(to='program.Member'),
        ),
        migrations.AlterField(
            model_name='event',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager', to='program.member'),
        ),
    ]
